blank_issues_enabled: false
issue_templates:
  - name: "Game Suggestions"
    description: "Suggest a game for the Telegram Claim Bot. Ensure it’s accessible via Telegram Web. Games needing virtual video gameplay, like racing or falling objects, may not be suitable."
    title: "Game Suggestion: [Your Game Name Here]"
    labels: ["suggestion", "game"]
    file: game-suggestions.md

  - name: "Bug Report"
    description: "Report a bug. Before reporting a bug, ensure you have completed all the steps in the troubleshooting guide to confirm the issue is not with your session."
    title: "Bug: [Describe the issue briefly]"
    labels: ["bug"]
    file: bug-report.md

  - name: "Feature Request"
    description: "Suggest a new feature to an existing game or request the modification of an existing feature."
    title: "Feature Request: [Describe your suggestion briefly]"
    labels: ["enhancement", "feature request"]
    file: feature-request.md

  - name: "General Help"
    description: "Request help. Before raising an issue, follow our step-by-step videos, detailed README, troubleshooting guide, and instructional guides."
    title: "Help Me: [Describe your issue briefly]"
    labels: ["help wanted", "support"]
    file: general-help.md
